### PR TITLE
sar marge mai pull requast sar I want free tsirt

### PR DESCRIPTION
**Pull request by malviscape**
sar i added bast pabg configs u should get 99999999999999999999999fps easily sar
marge pull requast plopx

[all's a joke]

### CODE REVIEW

**Comment by malviscape** [comment]
sar plis marge sar plis sar very apriciat sar

**Comment by 00p513-dev** [comment]
Sowwy no x86 on chungus. New phone s0n though

**Comment by malviscape** [comment]
i go die

**Comment by 00p513-dev** [comment]
check github.com/pru-inc

**Comment by malviscape** [comment]
https://github.com/malviscape/android_device_nostalgia_chungus/commit/7d67be6067421f3d6b73928cfddebe49efd6a52d

wen pick this

**Comment by 00p513-dev** [comment]
Never. make pr sur

**Comment by malviscape** [comment]
then i go die bye

**Pull request closed without merging**
